name: amass
summary: In-depth Attack Surface Mapping and Asset Discovery
description: |
  The OWASP Amass Project has developed a tool to help information 
  security professionals perform network mapping of attack surfaces 
  and external asset discovery using open source information gathering 
  and active reconnaissance techniques.
version: 'v3.18.2'
icon: images/snapcraft_icon.png
license: Apache-2.0	
base: core20
grade: stable
confinement: strict
architectures:
  - build-on: [s390x, ppc64el, arm64, armhf and amd64]
    run-on: [s390x, ppc64el, arm64, armhf and amd64]

apps:
  amass:
    command: bin/amass
    plugs:
      - home
      - network
      - removable-media
      - dot-amass

plugs:
  dot-amass:
    interface: personal-files
    write:
      - $HOME/.amass
      - $HOME/.config/amass

parts:
  amass:
    source: https://github.com/OWASP/Amass.git
    plugin: go
    go-channel: latest/stable